/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lab1.java-application-conventions")
    id("io.freefair.lombok") version "8.6"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":banks"))
    implementation("org.jline:jline:3.25.1")
    implementation("io.reactivex.rxjava3:rxjava:3.1.8")
}

application {
    // Define the main class for the application.
    mainClass.set("lab1.app.App")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
    standardOutput = System.`out`
}
