/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lab1.java-library-conventions")
    id("io.freefair.lombok") version "8.6"
}

dependencies {
    implementation("io.reactivex.rxjava3:rxjava:3.1.8")
}
